item {id: 1, name: "opossum"}
item {id: 2, name: "badger"}
item {id: 3, name: "raccoon"}
item {id: 4, name: "car"}
item {id: 5, name: "squirrel"}
item {id: 6, name: "bobcat"}
item {id: 7, name: "skunk"}
item {id: 8, name: "dog"}
item {id: 9, name: "coyote"}
item {id: 10, name: "rabbit"}
item {id: 11, name: "bird"}
item {id: 12, name: "deer"}
item {id: 13, name: "fox"}
item {id: 14, name: "rodent"}
item {id: 15, name: "cat"}
item {id: 16, name: "empty"}


