item {id: 1, name: "opossum"}
item {id: 3, name: "raccoon"}
item {id: 5, name: "squirrel"}
item{id: 6, name: "bobcat"}
item {id: 7, name: "skunk"}
item {id: 8, name: "dog"}
item {id: 9, name: "coyote"}
item {id: 10, name: "rabbit"} 
item {id: 11, name: "bird"}
item {id: 16, name: "cat"}
item {id: 21, name: "badger"}
item {id: 30, name: "empty"}
item {id: 33, name: "car"}
item {id: 34, name: "deer"}
item {id: 51, name: "fox"}
item {id: 99, name: "rodent"}